language: go
go:
    - 1.5
    - 1.6
install:
    - go get github.com/matannoam/comicjerk/carbonitexplugin
    - go get github.com/matannoam/comicjerk/chartplugin
    - go get github.com/matannoam/comicjerk/comicplugin
    - go get github.com/matannoam/comicjerk/directmessageinviteplugin
    - go get github.com/matannoam/comicjerk/discordavatarplugin
    - go get github.com/matannoam/comicjerk/inviteplugin
    - go get github.com/matannoam/comicjerk/reminderplugin
    - go get github.com/matannoam/comicjerk/statsplugin
    - go get github.com/matannoam/comicjerk
    - go get -v .
